FROM openjdk:8-jre
MAINTAINER lenyo 554307876@qq.com
COPY /target/hello-spring-cloud-alibaba-nacos-consumer-feign-1.0-SNAPSHOT.jar /NacosConsumerFeign.jar
ENTRYPOINT ["java","-jar","/NacosConsumerFeign.jar"]