spring:
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.80.229:8848
    sentinel:
          transport:
            port: 8720
            dashboard: 192.168.80.229:8858

server:
  port: 9092
#熔断器配置
feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
