spring:
  application:
    name: xxl-job-executor

server:
  port: 8088

#xxl-job 配置

# log config
logging:
  config: classpath:logback.xml


### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin.addresses: http://192.168.80.229:7070/xxl-job-admin
    ### xxl-job, access token
    accessToken:
### xxl-job executor appname
    executor:
      appname: xxl-job-executor-k8s-demo
### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
      address:
### xxl-job executor server-info
      ip:
      port: 9999
### xxl-job executor log-path
      logpath: /data/applogs/xxl-job/jobhandler
### xxl-job executor log-retention-days
      logretentiondays: 30
#熔断器配置
feign:
  sentinel:
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
